[project]
name = "blog"
version = "0.1.0"
description = ""
authors = [{name = "Thomas MK", email = "tmke@posteo.net"}]
requires-python = ">=3.10"
dependencies = [
    "pelican[markdown]>=4.11.0",
    "pygments>=2.18.0",
    "typogrify>=2.1.0",
]
